# Limpeza 


Foi feita uma limpeza prévia nos dados pelo excel, tendo em vista o prazo para entrega do projeto, se mostrou a forma mais rápida de obter o Input na estrutura correta.

## Importar Bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



## Importar base de dados

In [ ]:

dataset = pd.read_csv('Data_Sus.csv')



x=dataset.iloc[ : , :-1].values
#x são tipicamente as features e y as variáveis dependentes.

#Da mesma forma então:
y=dataset.iloc[ : ,-1].values




In [ ]:
print(x)
#Confirmando

[[1.30200e+03 5.87660e+05 1.41205e+05 5.59800e+02 3.61200e+03 3.20000e+01]
 [4.48000e+02 2.42512e+05 5.31150e+04 6.59880e+02 1.39900e+03 3.00000e+00]
 [3.61000e+02 1.78459e+05 3.77040e+04 5.98790e+02 9.11000e+02 4.00000e+00]
 ...
 [1.30300e+03 8.03741e+05 1.83504e+05 7.57670e+02 3.16500e+03 6.20000e+01]
 [8.30000e+02 3.06214e+05 7.11800e+04 4.54690e+02 2.50000e+03 1.20000e+01]
 [2.99000e+02 1.42687e+05 3.85370e+04 6.06100e+02 6.56000e+02 1.00000e+01]]


In [ ]:
print(y)
#Confirmando

[728865 295627 216163 ... 987246 377394 181225]


## Dados Faltando

In [ ]:

from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 


imputer.fit(x[:,1:7]) 


#Agora precisamos dar o intervalo em que queremos aplicar o critério de sunbstituição, no caso, a média:
x[:, 1:7] = imputer.transform(x[:, 1:7]) 



In [ ]:
print(x)
#nota-se que agora onde era nulo(nan), se substituiu pela média dos componentes da coluna:

[[1.30200e+03 5.87660e+05 1.41205e+05 5.59800e+02 3.61200e+03 3.20000e+01]
 [4.48000e+02 2.42512e+05 5.31150e+04 6.59880e+02 1.39900e+03 3.00000e+00]
 [3.61000e+02 1.78459e+05 3.77040e+04 5.98790e+02 9.11000e+02 4.00000e+00]
 ...
 [1.30300e+03 8.03741e+05 1.83504e+05 7.57670e+02 3.16500e+03 6.20000e+01]
 [8.30000e+02 3.06214e+05 7.11800e+04 4.54690e+02 2.50000e+03 1.20000e+01]
 [2.99000e+02 1.42687e+05 3.85370e+04 6.06100e+02 6.56000e+02 1.00000e+01]]


In [ ]:
print(y)

[728865 295627 216163 ... 987246 377394 181225]


## Dados categoricos

### Encoding the Independent Variable (Features)

In [ ]:
from sklearn.compose import ColumnTransformer 

from sklearn.preprocessing import OneHotEncoder 
#usamos o nome 'passthrough'que diz que as iformações não transformadas não serão tocadas).
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') #objeto


#A seguir precisamos que as matrizes estejam em formato de array para mais tarde. Então faremos  
# uso do numpy:

x= np.array(ct.fit_transform(x))
#a função fit_transform() tanto transforma, quanto encaixa os dados transformados no lugar.



In [ ]:
print(x)
#Conferindo

  (0, 0)	1.0
  (0, 3093)	1302.0
  (0, 3094)	587660.41
  (0, 3095)	141205.44
  (0, 3096)	559.8
  (0, 3097)	3612.0
  (0, 3098)	2.8
  (0, 3099)	32.0
  (0, 3100)	2.46
  (1, 24)	1.0
  (1, 3093)	448.0
  (1, 3094)	242512.04
  (1, 3095)	53115.22
  (1, 3096)	659.88
  (1, 3097)	1399.0
  (1, 3098)	3.1
  (1, 3099)	3.0
  (1, 3100)	0.67
  (2, 25)	1.0
  (2, 3093)	361.0
  (2, 3094)	178459.45
  (2, 3095)	37704.2
  (2, 3096)	598.79
  (2, 3097)	911.0
  (2, 3098)	2.5
  :	:
  (3090, 3094)	803741.89
  (3090, 3095)	183504.3
  (3090, 3096)	757.67
  (3090, 3097)	3165.0
  (3090, 3098)	2.4
  (3090, 3099)	62.0
  (3090, 3100)	4.76
  (3091, 3091)	1.0
  (3091, 3093)	830.0
  (3091, 3094)	306214.07
  (3091, 3095)	71180.31
  (3091, 3096)	454.69
  (3091, 3097)	2500.0
  (3091, 3098)	3.0
  (3091, 3099)	12.0
  (3091, 3100)	1.45
  (3092, 3092)	1.0
  (3092, 3093)	299.0
  (3092, 3094)	142687.77
  (3092, 3095)	38537.28
  (3092, 3096)	606.1
  (3092, 3097)	656.0
  (3092, 3098)	2.2
  (3092, 3099)	10.0
  (3092, 3100)	3.34


In [ ]:
print(y)

[728865.85 295627.26 216163.65 ... 987246.19 377394.38 181225.05]


### Encoding the Dependent Variable

In [ ]:

from sklearn.preprocessing import LabelEncoder 
le= LabelEncoder() 
y=le.fit_transform(y)


#OBS: como y não foi transformado em vetor, não é necessária a converção em array.



In [ ]:
print(y)

[1901 1276 1043 ... 2097 1459  914]


## Splitting the dataset into the Training set and Test set

Se a feature scaling fosse válida para análise de multivariável, o split de teste/treino seria antes da padronização. O que não é o caso. 

In [ ]:

from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=1)



In [ ]:
print(x_train)

[[1.03320000e+04 2.84092880e+07 7.50644800e+06 3.47617000e+03
  5.46460000e+04 8.90000000e+02]
 [1.66800000e+03 5.08816600e+06 9.19672000e+05 3.60182000e+03
  8.17100000e+03 1.83000000e+02]
 [2.17400000e+03 1.64719100e+06 2.95713000e+05 8.93700000e+02
  1.38100000e+04 2.51000000e+02]
 ...
 [2.96000000e+02 1.55905000e+05 4.58820000e+04 6.81720000e+02
  8.19000000e+02 1.50000000e+01]
 [1.74000000e+02 7.54400000e+04 1.48160000e+04 5.18710000e+02
  5.40000000e+02 2.92733821e+02]
 [2.89700000e+03 1.32841000e+06 5.09035000e+05 6.34260000e+02
  1.16180000e+04 2.36000000e+02]]


In [ ]:
print(y_train)



[35915737  6007839  1942905 ...   201788    90256  1837446]


In [ ]:
print(x_test)

[[1.07700e+03 5.21344e+05 1.32072e+05 6.06700e+02 2.70900e+03 4.00000e+01]
 [1.39800e+03 3.64730e+05 9.14410e+04 3.26300e+02 3.42300e+03 6.80000e+01]
 [1.45000e+03 5.66283e+05 1.87652e+05 5.26820e+02 3.72400e+03 2.00000e+00]
 ...
 [5.40000e+02 2.06951e+05 5.19400e+04 4.79430e+02 1.31300e+03 1.80000e+01]
 [1.40000e+01 8.28200e+03 1.39200e+03 6.91030e+02 5.00000e+01 2.00000e+00]
 [2.32000e+02 9.85810e+04 1.81520e+04 5.03160e+02 8.11000e+02 1.20000e+01]]


In [ ]:
print(y_test)



[    653416     456172     763890   20636891      29536     466466
      22791   87838291    1006227     312152     458077     277787
      84541     484919     272539    1647704     149411    6298912
     338739     150751    4205252     198857      27128     160485
     639182     277541      63706  152609294     327214    3688725
     370507    1305098    2591342      24169      74603     404084
      47707      40260     100394     321194   21142883      89989
     146815     274509     357010     261626    5286465   43786661
     111911     462638    7128889     984977    3663247  215533009
     652890     139669    1448806    1060087    7483898     309128
      33554     114856     157930     670022     171101      24422
    5175434    2294975     210980     148095     387886     223200
   12634702     174681     743546     163578      50046     184946
      69080      82556    1022884  160146616     445490    2175636
      31291      45740     107344     343158   18853155     14

## Treinando Multipla regressão linear na base de treinamento

In [ ]:
from sklearn.linear_model import LinearRegression 
regressor= LinearRegression() 

regressor.fit(x_train,y_train)

#A classe LinearRegression já resolve o famoso problema da Dummy Variable.

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Prevendo resultado de teste

In [ ]:
prev_y= regressor.predict(x_test)
np.set_printoptions(precision=2)

print(np.concatenate((prev_y.reshape(len(prev_y),1), y_test.reshape(len(y_test),1)),1))


[[651920.7  653416.  ]
 [456238.01 456172.  ]
 [755628.78 763890.  ]
 ...
 [254942.41 258891.  ]
 [  3099.06   9674.  ]
 [111043.68 116734.  ]]


In [ ]:
print(regressor.coef_)
print(regressor.intercept_)

#printamos assim todaos os coeficientes, que é o nosso objetivo aqui.

[  6.7    1.     1.01   0.05  -0.32 -17.76]
-6638.096226314083
<bound method BaseEstimator.set_params of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)>


In [ ]:
prev_y= regressor.predict(x_test)
np.set_printoptions(precision=2)

print(np.concatenate((prev_y.reshape(len(prev_y),1), y_test.reshape(len(y_test),1)),1))
#Serve para comparação visual da precisão de previsão.

[[651920.7  653416.  ]
 [456238.01 456172.  ]
 [755628.78 763890.  ]
 ...
 [254942.41 258891.  ]
 [  3099.06   9674.  ]
 [111043.68 116734.  ]]
